# Generated by Django 3.2.6 on 2021-08-11 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_dpt', models.CharField(help_text='Enter the department of the employee', max_length=300, unique=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='emp_data',
            fields=[
                ('EmpId', models.AutoField(primary_key=True, serialize=False)),
                ('EmpName', models.CharField(help_text='Enter the name of the employee', max_length=250)),
                ('Age', models.IntegerField(help_text='Enter the age of the employee')),
                ('DeptName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
            ],
            options={
                'ordering': ['EmpId'],
            },
        ),
    ]
